### PR TITLE
HTML/CSS for main events page created, basic view implemented (ListView)

### PR DESCRIPTION
**Pull request by MufasaTheMusician**
Main event page is ready to go - haven't tested on mobile, but it all seems to work when the window gets resized big or small.

In terms of style, pretty much followed the UI layout to the letter but shortened the Create Event button horizontally just a bit and applied stronger rounded corners on the bottom of an event compared to the top just to give the events a bit of definition between each other when scrolling and looking side by side.

Wasn't quite sure whether we want the banner to stay at the top of the page or to come for the ride as people scroll down a long list of events, so for now it sits at the top and can be changed if needed.

Create Event button is an input tag and just needs to link to the relevant form when created. Events are displayed in a CSS grid and the outline template boxes are already set up - when the EventView is created, the div tags used can be copied into the "event" div tag and the items will conform to the box and the list.

Should also note that CSS grids are quite flexible, so if we want to implement more views in the future (grid, 2 columns etc.) this can be achieved with a small modification to the columns defined.
(The top banner also uses a grid, so things can be moved to make room for new buttons as needed)

If we want to make changes in terms of spacing, text size, borders etc. it's all pretty straightforward, just let me know.

(Also added a sneaky link to the Guild website in the logo :) )

### CODE REVIEW

**Comment by mrpresidentjk** [comment]
Looks good, I am happy to approve and merge. I may wait till Friday to merge so that I can clarify whether we want mobile working as MVP but I don't think we need to. I tried to see what it looks like by using chromes device simulator in the inspect page option. 
screenshot from 2018-08-22 21-05-22
Its small and definitely needs to be fixed for the final thing but its still usable for now (MVP).

**Comment by mrpresidentjk** [comment]
I added bootstrap to the project. To use it:
1. Place this at the beginning of your template file:
`{% load static %}`
2. Include the following as a style sheet in your template:
`<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">`
Try get the web page working with the bootstrap card component found [here](https://getbootstrap.com/docs/4.0/components/card/). This will ensure that our website is compatible with mobile devices. 
If this does not work or is too much work then we will not include it in the MVP and I will merge this pull request.

**Comment by mrpresidentjk** [comment]
I should probably talk to you guys in person about some of this stuff, but I had a few thoughts while implementing my own stuff. Its best that we use bootstrap components as a basis as well because it supports a bunch of tools for generating themes easily that we can immediately install. I think for now we should not worry about the colours and focus on getting the layout correct using bootstrap.

**Comment by MufasaTheMusician** [comment]
Looks good, I'll give it a shot and change my stuff over, then we know for sure the site works for all devices since it's an industry standard. Sounds like it will be easier to implement the design team's theme consistently with those generating tools. 

I'll update issue 8 to include bootstrap, we can leave this one here in case it gets weird and we need to revert.

**Comment by MufasaTheMusician** [comment]
[Implement Demo MVP Events Grid Component](https://trello.com/c/Rvv7FAm1/70-implement-demo-mvp-events-grid-component)

**Pull request merged**
